name: flutter_keychain_example
description: "Demonstrates how to use the flutter_keychain plugin."
publish_to: 'none'

version: 3.0.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_keychain:
    path: ../

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true